Style/Documentation:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

AllCops:
  Exclude:
    - spec/dummy/**/*


Naming/FileName:
  Exclude:
    - lib/activestorage-delayed.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - db/migrate/*