version: '2'

services:
  test:
    build: .
    environment:
      RAILS_ENV: test
    command: sh -c 'bundle exec rspec'
    volumes:
      - .:/app
      - bundler_gems:/usr/local/bundle/

volumes:
  bundler_gems: